name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Ensure this matches your branch name (could be 'master')

  workflow_dispatch:  # Allows manual triggering from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Test across multiple Node.js versions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Cache dependencies for faster builds

      - name: Install Dependencies
        run: npm ci  # Ensures a clean and deterministic install

      - name: Run Linter
        run: npm run lint  # Optional: Ensures code quality with ESLint

      - name: Build Project
        run: npm run build

      - name: Upload Production Files
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: ./build  # Upload the 'build/' directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Add this secret in your repo settings
          publish_dir: ./build  # Directory containing the compiled app
          user_name: 'GitHub Actions Bot'  # Optional: Commits by this bot
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
